{
    'name': 'YSave Sacco Import',
    'version': '1.0',
    'summary': 'Module to import Excel data and create journal entries for savings, shares, and loans',
    'depends': [
        'base',
        'account',
        'savings_management',
        'shares_management',
        'sacco_loan_management',
        'investments_management',
        'member_management',
    ],
    'data': [
        'security/ir.model.access.csv',
        # 'wizards/import_wizard_view.xml',
        # 'wizards/savings_product_wizard_view.xml',
        # 'wizards/investments_product_wizard_view.xml',
        # 'wizards/loan_product_wizard_view.xml',
        # 'wizards/theadid_import_wizard_view.xml',
        # 'wizards/process_journal_entries_wizard_view.xml',
        # 'wizards/process_loan_journal_entries_wizard_view.xml',
        # 'wizards/member_import_wizard_view.xml',
        # 'wizards/chart_accounts_import_wizard_view.xml',
        # 'wizards/product_accounts_import_wizard_view.xml',
        # 'wizards/loans_import_wizard_view.xml',
        # 'wizards/import_members_view.xml',
        'wizards/import_journal_entry_by_year_view.xml',
    ],
    'installable': True,
    'application': False,
}