{
    'name': 'SACCO Transactions Management',
    'version': '1.0',
    'sequence': 2,
    'summary': 'Base module for SACCO operations',
    'description': 'Common models and fields for SACCO modules',
    'category': 'Accounting',
    'author': "Omni Software Ltd",
    'company': "Omni Software Ltd",
    'website': "https://www.omnitech.co.ug",
    'depends': ['base', 'mail', 'account', 'account_reports', 'web', 'member_management'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/account_journal_data.xml',
        'views/menu_views.xml',
        'views/general_member_statement_wizard_views.xml',
        'views/member_ledger_report.xml',
        'views/receiving_account_views.xml',
        'views/paying_account_views.xml',
        'views/general_transactions_views.xml',
        'views/general_transactions_history_views.xml',
        'views/account_views.xml',
        'views/account_move_views.xml',
        'views/background_jobs_views.xml',
        'reports/member_statement_report.xml',
        'data/cron.xml',
    ],
    'assets': {
            'web.assets_backend': [
                'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&display=swap',
                'sacco_transactions_management/static/src/js/transactions_view.js',
                'sacco_transactions_management/static/src/xml/transactions_view.xml',
                'sacco_transactions_management/static/src/css/transactions_view.css',
                'sacco_transactions_management/static/src/xml/member_ledger_line_name.xml',
            ],
        },
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
    # 'post_init_hook': 'post_init_hook',
}