from . import account_move_line
from . import api_token_mixin
from . import loan_proof
from . import loan_type
from . import res_partner
from . import sacco_loan_loan
from . import sacco_loan_installment
from . import sacco_loan_payments
from . import res_company
from . import res_config_setting
from . import sacco_loan_payment_sync
from . import loan_product_sync
from . import loan_applications_mis
from . import sacco_loan_interest
from . import sacco_loans_journal_account_line
from . import loans_product_mis
from . import loan_proofs_mis
from . import loan_guarantor
from . import loan_security
