{
    'name': 'Savings Management',
    'version': '1.0',
    'sequence': 2,
    'summary': 'Helps You To Manage Savings operations',
    'description': 'Manage Savings operations',
    'category': 'Accounting',
    'author': "Omni Software Ltd",
    'company': "Omni Software Ltd",
    'website': "https://www.omnitech.co.ug",
    'depends': ['base', 'mail', 'account', 'web', 'sacco_transactions_management'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'edi/mail_template.xml',
        'views/savings_management_menu.xml',
        'wizards/withdrawal_request_reject_view.xml',
        'wizards/savings_statement_wizard_view.xml',
        'views/savings_product_views.xml',
        'views/savings_account_views.xml',
        'views/withdrawal_request_views.xml',
        'views/savings_transaction_views.xml',
        'views/interest_posting_views.xml',
        'views/res_partner_views.xml',
        'report/savings_statement_templates.xml',
    ],
    'demo': [],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}